using AIRadio.Server.Models.Audio;

namespace AIRadio.Server.Services.Audio
{
    /// <summary>
    /// Defines the types of audio events processed by the AudioManager.
    /// </summary>
    public enum AudioEventType
    {
        /// <summary>
        /// Text that should be converted to speech using the configured
        /// text-to-speech engine.
        /// </summary>
        Speech = 0,

        /// <summary>
        /// Plays a pre-recorded WAV audio event or sound effect.
        /// </summary>
        WaveEffect = 1,

        /// <summary>
        /// Executes a media control command such as Duck, Resume or Stop.
        /// </summary>
        MediaCommand = 2,

        /// <summary>
        /// Blocks processing until all queued audio has completed playback.
        /// </summary>
        WaitForCompletion = 3
    }

    /// <summary>
    /// Represents a single unit of work processed by the AudioManager.
    /// </summary>
    public sealed class AudioEvent
    {
        /// <summary>
        /// Gets the type of audio event.
        /// </summary>
        public AudioEventType Type { get; init; }


        /// <summary>
        /// Gets the text to be synthesized.
        /// Used by Speech events.
        /// </summary>
        public string? Text { get; init; }


        /// <summary>
        /// Gets the name of the sound effect to play.
        /// Used by WaveEffect events.
        /// Examples: "startup", "error", "notification"
        /// </summary>
        public string? SoundName { get; init; }


        /// <summary>
        /// Gets the media control command.
        /// Used by MediaCommand events.
        /// </summary>
        public AudioCommand? Command { get; init; }


        /// <summary>
        /// Gets an optional identifier used for diagnostics and logging.
        /// </summary>
        public string? EventId { get; init; }


        /// <summary>
        /// Gets the UTC time the event was created.
        /// </summary>
        public DateTimeOffset TimestampUtc { get; init; }
            = DateTimeOffset.UtcNow;


        public override string ToString()
        {
            return Type switch
            {
                AudioEventType.Speech =>
                    $"Speech: \"{Text}\"",

                AudioEventType.WaveEffect =>
                    $"WaveEffect: {SoundName}",

                AudioEventType.MediaCommand =>
                    $"MediaCommand: {Command?.Type}",

                AudioEventType.WaitForCompletion =>
                    "WaitForCompletion",

                _ =>
                    Type.ToString()
            };
        }


        #region Factory Methods

        public static AudioEvent Speech(
            string text) =>
            new()
            {
                Type = AudioEventType.Speech,
                Text = text
            };


        public static AudioEvent WaveEffect(
            string soundName) =>
            new()
            {
                Type = AudioEventType.WaveEffect,
                SoundName = soundName
            };


        public static AudioEvent MediaCommand(
            AudioCommand command) =>
            new()
            {
                Type = AudioEventType.MediaCommand,
                Command = command
            };


        public static AudioEvent WaitForCompletion() =>
            new()
            {
                Type = AudioEventType.WaitForCompletion
            };

        #endregion
    }

    /// <summary>
    /// Represents the audio portion of a model response before it has been
    /// parsed into executable audio events.
    /// </summary>
    public sealed class ModelAudioResponse
    {
        /// <summary>
        /// Gets or sets the raw response text generated by the model.
        /// The text may contain embedded audio directives such as:
        ///
        /// Hello there.
        /// {sound:startup}
        /// {media:duck}
        /// </summary>
        public string Text { get; init; } = string.Empty;


        /// <summary>
        /// Gets or sets an optional identifier used for diagnostics
        /// and correlating log entries.
        /// </summary>
        public string? ResponseId { get; init; }


        /// <summary>
        /// Gets or sets the UTC time the response was generated.
        /// </summary>
        public DateTimeOffset TimestampUtc { get; init; }
            = DateTimeOffset.UtcNow;


        /// <summary>
        /// Gets whether the response contains any text.
        /// </summary>
        public bool HasContent =>
            !string.IsNullOrWhiteSpace(Text);


        /// <summary>
        /// Gets the length of the response text.
        /// </summary>
        public int Length =>
            Text.Length;


        public override string ToString() =>
            $"ResponseId={ResponseId ?? "<none>"}, Length={Length}";
    }
}
