using AIRadio.Server.Models.LLama;
using Newtonsoft.Json;

namespace AIRadio.Server.Models.Tools
{
    public enum ToolResultStatus
    {
        Result,
        MissingParameter,
        Preamble
    }

    public sealed class ToolResult
    {
        public string ToolName { get; set; } = string.Empty;

        public ToolResultStatus Status { get; set; }

        public bool Success { get; set; }

        public string? Message { get; set; }

        public object? Data { get; set; }

        /// <summary>
        /// Direct speech for MissingParameter or Preamble.
        /// May contain embedded sound-effect tags.
        /// </summary>
        public string? ExactPrompt { get; set; }

        /// <summary>
        /// Tool request to resume after MissingParameter or Preamble.
        /// </summary>
        public ToolRequest? PendingRequest { get; set; }

        public string? Error { get; set; }

        /// <summary>
        /// Optional isolated Llama commands generated by the tool. Commands are
        /// processed sequentially and each command can produce speech independently.
        /// </summary>
        public IReadOnlyList<LlmCommand> LlmCommands { get; set; } = [];

        /// <summary>
        /// Formats the successful tool data as a compact, human-readable report
        /// intended for the response LLM. The structured Data remains available
        /// to application code and logging.
        /// </summary>
        public string ToReport() =>
            ToolReportFormatter.Format(ToolName, Data, Message);

        public string ToJson() =>
            JsonConvert.SerializeObject(this, Formatting.None);

        public static ToolResult Successful(
            string toolName,
            string? message = null,
            object? data = null,
            string? exactPrompt = null)
        {
            return new ToolResult
            {
                ToolName = toolName,
                Status = ToolResultStatus.Result,
                Success = true,
                Message = message,
                Data = data,
                ExactPrompt = exactPrompt
            };
        }

        public static ToolResult SuccessfulWithLlmCommands(
            string toolName,
            IEnumerable<LlmCommand> commands,
            string? message = null)
        {
            ArgumentNullException.ThrowIfNull(commands);

            var commandList = commands.ToList();
            if (commandList.Count == 0)
                throw new ArgumentException("At least one LLM command is required.", nameof(commands));

            return new ToolResult
            {
                ToolName = toolName,
                Status = ToolResultStatus.Result,
                Success = true,
                Message = message,
                LlmCommands = commandList
            };
        }

        public static ToolResult Failed(
            string toolName,
            string error,
            string? exactPrompt = null,
            ToolRequest? pendingRequest = null)
        {
            return new ToolResult
            {
                ToolName = toolName,
                Status = ToolResultStatus.Result,
                Success = false,
                Error = error,
                ExactPrompt = exactPrompt,
                PendingRequest = pendingRequest
            };
        }

        public static ToolResult MissingParameter(
            string toolName,
            string prompt,
            ToolRequest pendingRequest)
        {
            ArgumentNullException.ThrowIfNull(pendingRequest);

            return new ToolResult
            {
                ToolName = toolName,
                Status = ToolResultStatus.MissingParameter,
                Success = false,
                ExactPrompt = prompt,
                PendingRequest = pendingRequest
            };
        }

        public static ToolResult Preamble(
            string toolName,
            string prompt,
            ToolRequest continuation)
        {
            ArgumentNullException.ThrowIfNull(continuation);

            return new ToolResult
            {
                ToolName = toolName,
                Status = ToolResultStatus.Preamble,
                Success = true,
                ExactPrompt = prompt,
                PendingRequest = continuation
            };
        }
    }
}