using AIRadio.Server.Models.LLama;
using AIRadio.Server.Models.Tools;
using AIRadio.Server.Services.AI;
using AIRadio.Server.Services.Audio;

namespace AIRadio.Server.Services.Radio
{
    public interface IConversationService
    {
        Task ProcessAsync(string text, CancellationToken cancellationToken = default);
        Task CancelAsync(CancellationToken cancellationToken = default);
    }

    public sealed class ConversationService : IConversationService, IAsyncDisposable
    {
        private readonly ILogger<ConversationService> _logger;
        private readonly IConversationLlamaClient _llama;
        private readonly IAudioManager _audioManager;
        private readonly IReadOnlyDictionary<string, ITool> _tools;
        private readonly AsyncWorkQueue<ConversationRequest> _queue;

        public ConversationService(ILogger<ConversationService> logger, IConversationLlamaClient llama, IAudioManager audioManager, IEnumerable<ITool> tools)
        {
            _logger = logger;
            _llama = llama;
            _audioManager = audioManager;
            ArgumentNullException.ThrowIfNull(tools);
            _tools = tools.ToDictionary(tool => tool.Name, StringComparer.OrdinalIgnoreCase);
            _queue = new AsyncWorkQueue<ConversationRequest>();
            _queue.Start(ProcessRequestAsync);
        }

        public Task ProcessAsync(string text, CancellationToken cancellationToken = default)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(text);
            cancellationToken.ThrowIfCancellationRequested();
            if (!_queue.TryEnqueue(new ConversationRequest(text)))
                _logger.LogDebug("Conversation request rejected because the conversation queue is not accepting work.");
            return Task.CompletedTask;
        }

        public async Task CancelAsync(CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            await _queue.CancelAsync(CancellationToken.None);
            await _audioManager.CancelAsync(CancellationToken.None);
            _queue.Resume();
        }

        private async Task ProcessRequestAsync(ConversationRequest request, CancellationToken cancellationToken)
        {
            try
            {
                var response = _llama.IsInitialized
                    ? await _llama.ContinueAsync(request.Text, cancellationToken)
                    : await _llama.StartConversationAsync(request.Text, cancellationToken);

                await ProcessLlamaResponseAsync(response, cancellationToken);

                await _audioManager.EndUtteranceAsync(cancel: false, cancellationToken);
                _logger.LogInformation("llama utterance is complete");
            }
            catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
            {
                _logger.LogDebug("Conversation processing cancelled.");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Conversation processing failed.");
            }
        }

        private async Task ProcessLlamaResponseAsync(LlamaResponse response, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            // Sound tags are part of SpokenText and AudioManager parses them in
            // place, preserving the exact order generated by Llama. Tool
            // requests are a separate side channel and can execute while speech
            // is being generated/queued.
            var speechTask = response.HasSpeech
                ? _audioManager.PlaySpeechAsync(response.SpokenText, cancellationToken)
                : Task.CompletedTask;

            var toolTask = response.HasToolRequests
                ? ExecuteToolsAsync(response.ToolRequests, cancellationToken)
                : Task.CompletedTask;

            await Task.WhenAll(speechTask, toolTask);
        }

        private async Task ExecuteToolsAsync(IEnumerable<ToolRequest> toolRequests, CancellationToken cancellationToken)
        {
            var requests = toolRequests.ToList();
            if (requests.Count == 0) return;

            // Tool directives are independent of the spoken stream. Execute
            // independent requests concurrently and preserve request ordering
            // in the result list returned to Llama.
            var resultTasks = requests.Select(request => ExecuteToolAsync(request, cancellationToken)).ToArray();
            var results = await Task.WhenAll(resultTasks);
            cancellationToken.ThrowIfCancellationRequested();

            var response = await _llama.ContinueAsync(results, cancellationToken);
            await ProcessLlamaResponseAsync(response, cancellationToken);
        }

        private async Task<ToolResult> ExecuteToolAsync(ToolRequest request, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (string.IsNullOrWhiteSpace(request.Name))
                return ToolResult.Failed("tool_dispatcher", "The tool request did not specify a tool name.");

            if (!_tools.TryGetValue(request.Name, out var tool))
                return ToolResult.Failed("tool_dispatcher", $"Tool '{request.Name}' is not available.");

            try
            {
                var result = await tool.ExecuteAsync(request, cancellationToken);
                return result ?? ToolResult.Failed(request.Name, $"Tool '{request.Name}' returned no result.");
            }
            catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
            {
                throw;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Tool {ToolName} failed.", request.Name);
                return ToolResult.Failed(request.Name, ex.Message);
            }
        }

        public ValueTask DisposeAsync() => _queue.DisposeAsync();

        private sealed record ConversationRequest(string Text);
    }
}
